version: "3.8"

## DBのローカル構築はこちらを参照
## https://neon.tech/guides/local-development-with-neon#local-postgresql
## ただし, volumeのみマウント場所がProjectRootになるように変更している
services:
  postgres:
    image: postgres:17
    command: "-d 1"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  neon-proxy:
    image: ghcr.io/timowilhelm/local-neon-http-proxy:main
    environment:
      - PG_CONNECTION_STRING=postgres://postgres:postgres@postgres:5432/main
    ports:
      - "4444:4444"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
      - ./package.json:/app/package.json
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./tsconfig.base.json:/app/tsconfig.base.json
      - ./Makefile:/app/Makefile
      - /app/frontend/node_modules
    env_file:
      - ./env/.env.frontend
    command: make start_frontend

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8787:8787"
    volumes:
      - ./backend:/app/backend
      - ./package.json:/app/package.json
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./tsconfig.base.json:/app/tsconfig.base.json
      - ./Makefile:/app/Makefile
      - /app/backend/node_modules
    env_file:
      - ./env/.env.backend
    command: make start_backend-dev
    depends_on:
      postgres:
        condition: service_healthy
